cmake_minimum_required(VERSION 4.1)
project(CPP_Level_2)

set(CMAKE_CXX_STANDARD 14)

include_directories(CPPM4-Dynamic-Array-Implementation)
include_directories(CPPM4-Grocery-List)
include_directories(CPPM5-Matrix-Fun-with-Matrix-Class)
include_directories(CPPM5-Profile-Posts)

add_executable(CPP_Level_2
#        CPPM1-Pointers/main.cpp
        CPPM1-Pointer-Practice/main.cpp
#        CPPM1-Pointer-Error-Examples/main.cpp
#        CPPM2-Array-Basics-Reference/main.cpp
#        CPPM2-Array-Practice/main.cpp
#        CPPM2-Pointer-Arithmetic-Reference/main.cpp
#        CPPM2-Tic-Tac-Toe/main.cpp
#        CPPM3-Two-Dimensional-Arrays-Reference/main.cpp
#        CPPM3-2D-Array-Practice/main.cpp
#        CPPM3-Bank-Transactions/main.cpp
#        CPPM4-Dynamic-Variables-Reference/main.cpp
#        CPPM4-Assembly-Line/main.cpp
#        CPPM4-Dynamic-Array-Implementation/DynamicArray.cpp
#        CPPM4-Dynamic-Array-Implementation/main.cpp
#        CPPM4-Grocery-List/DynamicArray.cpp
#        CPPM4-Grocery-List/GroceryList.cpp
#        CPPM4-Grocery-List/main.cpp
#        CPPM5-Matrix-Fun-with-Matrix-Class/main.cpp
#        CPPM5-Matrix-Fun-with-Matrix-Class/matrix.cpp
#        CPPM5-Profile-Posts/main.cpp
#        CPPM5-Profile-Posts/profile.cpp
)
